### ISSUE TITLE
Bug click material UI dans les thématiques

### ISSUE THREAD

**Issue by Mikoteko** [data-players/portail-alimentation-durable#29]
![Image](https://github.com/data-players/portail-alimentation-durable/assets/63355855/0b01c453-aaa6-44de-b66d-0a2cb88e060e)

**Comment by BastienSig** [comment]
Le fix qui avait été fait semble ne pas fonctionner certaine fois quand on clique sur la flèche

**Comment by BastienSig** [comment]
Décision, on passe en v5 pour tester
