### ISSUE TITLE
vérifier dans la base l'existence d'un champ territoire qui n'est pas remonté dans le portail

### ISSUE THREAD

**Issue by BastienSig** [data-players/portail-alimentation-durable#59]

**Comment by simonLouvet** [comment]
champ territoire dans la source agire pour une alimentaiton locale

**Comment by simonLouvet** [comment]
pas de champ territoire dans les metas. Voir si une colonne existe

**Comment by simonLouvet** [comment]
le champ dans les data : meta.contexte
